//
//  TripIcon.swift
//  Footprint
//
//  Created by sandy on 11/12/24.
//

import Foundation

enum TripIcon: String, Equatable, Hashable {
    case bread = "bread"
    case accountingBillStack = "accountingBillStack"
    case noTalking = "noTalking"
    case amusementPark = "amusementPark"
    case athleticsRunning = "athleticsRunning"
    case awardRibbonStar = "awardRibbonStar"
    case bandageLeg = "bandageLeg"
    case bicycle = "bicycle"
    case bookmark = "bookmark"
    case bus = "bus"
    case camera = "camera"
    case capsule = "capsule"
    case car = "car"
    case champagne = "champagne"
    case circle = "circle"
    case cloud = "cloud"
    case cloudSnow = "cloudSnow"
    case clover = "clover"
    case cocktail = "cocktail"
    case coffee = "coffee"
    case confetti = "confetti"
    case diamond = "diamond"
    case disapointed = "disapointed"
    case dislike = "dislike"
    case earthStar = "earthStar"
    case facebook = "facebook"
    case fire = "fire"
    case fitnessBicycle = "fitnessBicycle"
    case fitnessShaker = "fitnessShaker"
    case golfHole = "golfHole"
    case google = "google"
    case heart = "heart"
    case house = "house"
    case iceCream = "iceCream"
    case instagram = "instagram"
    case like = "like"
    case lol = "lol"
    case mad = "mad"
    case medical = "medical"
    case metro = "metro"
    case movie = "movie"
    case music = "music"
    case natural = "natural"
    case nightMoon = "nightMoon"
    case officeOutdoors = "officeOutdoors"
    case paperEdit = "paperEdit"
    case plane = "plane"
    case prank = "prank"
    case rankingStarsRibbon = "rankingStarsRibbon"
    case restaurantDishes = "restaurantDishes"
    case running = "running"
    case shoppingCart = "shoppingCart"
    case smile = "smile"
    case soccerField = "soccerField"
    case spaceAstronaut = "spaceAstronaut"
    case square = "square"
    case stampsImage = "stampsImage"
    case star = "star"
    case sun = "sun"
    case tags = "tags"
    case triangle = "triangle"
    case tripRoad = "tripRoad"
    case umbrella = "umbrella"
    case unhappy = "unhappy"
    case walking = "walking"
    case yoga = "yoga"
    case youtube = "youtube"
    
    var imageName: String {
        switch self {
        case .bread: return "ic_concept_bread"
        case .accountingBillStack: return "ic_concept_accountingBillStack"
        case .noTalking: return "ic_concept_Allowances-No-Talking--Streamline-Ultimate"
        case .amusementPark: return "ic_concept_amusementPark"
        case .athleticsRunning: return "ic_concept_athleticsRunning"
        case .awardRibbonStar: return "ic_concept_awardRibbonStar"
        case .bandageLeg: return "ic_concept_bandageLeg"
        case .bicycle: return "ic_concept_bicycle"
        case .bookmark: return "ic_concept_bookmark"
        case .bus: return "ic_concept_bus"
        case .camera: return "ic_concept_camera"
        case .capsule: return "ic_concept_capsule"
        case .car: return "ic_concept_car"
        case .champagne: return "ic_concept_champagne"
        case .circle: return "ic_concept_circle"
        case .cloud: return "ic_concept_cloud"
        case .cloudSnow: return "ic_concept_cloudSnow"
        case .clover: return "ic_concept_clover"
        case .cocktail: return "ic_concept_cocktail"
        case .coffee: return "ic_concept_coffee"
        case .confetti: return "ic_concept_confetti"
        case .diamond: return "ic_concept_diamond"
        case .disapointed: return "ic_concept_disapointed"
        case .dislike: return "ic_concept_dislike"
        case .earthStar: return "ic_concept_earthStar"
        case .facebook: return "ic_concept_facebook"
        case .fire: return "ic_concept_fire"
        case .fitnessBicycle: return "ic_concept_fitnessBicycle"
        case .fitnessShaker: return "ic_concept_fitnessShaker"
        case .golfHole: return "ic_concept_golfHole"
        case .google: return "ic_concept_google"
        case .heart: return "ic_concept_heart"
        case .house: return "ic_concept_house"
        case .iceCream: return "ic_concept_iceCream"
        case .instagram: return "ic_concept_instagram"
        case .like: return "ic_concept_like"
        case .lol: return "ic_concept_lol"
        case .mad: return "ic_concept_mad"
        case .medical: return "ic_concept_medical"
        case .metro: return "ic_concept_metro"
        case .movie: return "ic_concept_movie"
        case .music: return "ic_concept_music"
        case .natural: return "ic_concept_natural"
        case .nightMoon: return "ic_concept_nightMoon"
        case .officeOutdoors: return "ic_concept_officeOutdoors"
        case .paperEdit: return "ic_concept_paperEdit"
        case .plane: return "ic_concept_plane"
        case .prank: return "ic_concept_prank"
        case .rankingStarsRibbon: return "ic_concept_rankingStarsRibbon"
        case .restaurantDishes: return "ic_concept_restaurantDishes"
        case .running: return "ic_concept_running"
        case .shoppingCart: return "ic_concept_shoppingCart"
        case .smile: return "ic_concept_smile"
        case .soccerField: return "ic_concept_soccerField"
        case .spaceAstronaut: return "ic_concept_spaceAstronaut"
        case .square: return "ic_concept_square"
        case .stampsImage: return "ic_concept_stampsImage"
        case .star: return "ic_concept_star"
        case .sun: return "ic_concept_sun"
        case .tags: return "ic_concept_tags"
        case .triangle: return "ic_concept_triangle"
        case .tripRoad: return "ic_concept_tripRoad"
        case .umbrella: return "ic_concept_umbrella"
        case .unhappy: return "ic_concept_unhappy"
        case .walking: return "ic_concept_walking"
        case .yoga: return "ic_concept_yoga"
        case .youtube: return "ic_concept_youtube"
        }
    }
}
