//
//  CategoryIcon.swift
//  Footprint
//
//  Created by sandy on 10/24/24.
//

import Foundation

enum CategoryIcon: String, Equatable, Hashable {
    case activity_01_brush = "activity_01_brush"
    case activity_02_robot = "activity_02_robot"
    case activity_03_controller_wireless = "activity_03_controller_wireless"
    case activity_04_camera = "activity_04_camera"
    case activity_05_mike = "activity_05_mike"
    case activity_06_camera_video = "activity_06_camera_video"
    case activity_07_groupRunning = "activity_07_groupRunning"
    case activity_08_yoga = "activity_08_yoga"
    case activity_09_fitnessBicycle = "activity_09_fitnessBicycle"
    case activity_10_golfHole = "activity_10_golfHole"
    case activity_11_baseball_batBall = "activity_11_baseball_batBall"
    case activity_12_bowlingSet = "activity_12_bowlingSet"
    case activity_13_tambourine = "activity_13_tambourine"
    case activity_14_headphones = "activity_14_headphones"
    
    case daily_01_coffee_mug = "daily_01_coffee_mug"
    case daily_02_wine = "daily_02_wine"
    case daily_03_forkSpoon = "daily_03_forkSpoon"
    case daily_04_chicken = "daily_04_chicken"
    case daily_05_burger = "daily_05_burger"
    case daily_06_donut = "daily_06_donut"
    case daily_07_strawberry = "daily_07_strawberry"
    case daily_08_waterMelon = "daily_08_waterMelon"
    case daily_09_carrot = "daily_09_carrot"
    case daily_10_smoking = "daily_10_smoking"
    case daily_11_bicycle = "daily_11_bicycle"
    case daily_12_car = "daily_12_car"
    case daily_13_bus = "daily_13_bus"
    case daily_14_airplane = "daily_14_airplane"
    case daily_15_baggage = "daily_15_baggage"
    case daily_16_beach = "daily_16_beach"
    case daily_17_medicalBandage = "daily_17_medicalBandage"
    case daily_18_money = "daily_18_money"
    case daily_19_money_piggy = "daily_19_money_piggy"
    case daily_20_shoppingCart = "daily_20_shoppingCart"
    case daily_21_shoppingBasket = "daily_21_shoppingBasket"
    case daily_22_gift = "daily_22_gift"
    case daily_23_home = "daily_23_home"
    case daily_24_location_pin = "daily_24_location_pin"
    case daily_25_location_user = "daily_25_location_user"
    
    case emotion_01_emojiFace = "emotion_01_emojiFace"
    case emotion_02_emojiSad = "emotion_02_emojiSad"
    case emotion_03_emojiCheerful = "emotion_03_emojiCheerful"
    case emotion_04_emojiLol = "emotion_04_emojiLol"
    case emotion_05_emojiExcited = "emotion_05_emojiExcited"
    case emotion_06_emojiHungry = "emotion_06_emojiHungry"
    case emotion_07_emojiDevastated = "emotion_07_emojiDevastated"
    case emotion_08_alien = "emotion_08_alien"
    case emotion_09_skull = "emotion_09_skull"
    case emotion_10_chatSmiley = "emotion_10_chatSmiley"
    case emotion_11_handOk = "emotion_11_handOk"
    case emotion_12_thumbsUp = "emotion_12_thumbsUp"
    case emotion_13_star = "emotion_13_star"
    case emotion_14_heart = "emotion_14_heart"
    case emotion_15_heartBreak = "emotion_15_heartBreak"
    case emotion_16_chatSquare_warning = "emotion_16_chatSquare_warning"
    case emotion_17_chatSquare_question = "emotion_17_chatSquare_question"
    case emotion_18_magicWand = "emotion_18_magicWand"
    case emotion_19_twinkle = "emotion_19_twinkle"
    
    case etc_01_bookmark = "etc_01_bookmark"
    case etc_02_cursorArrow1 = "etc_02_cursorArrow1"
    case etc_03_cursorArrow2 = "etc_03_cursorArrow2"
    case etc_04_bell = "etc_04_bell"
    case etc_05_megaPhone = "etc_05_megaPhone"
    case etc_06_loading = "etc_06_loading"
    case etc_07_phone = "etc_07_phone"
    case etc_08_twoBubbles = "etc_08_twoBubbles"
    case etc_09_letter = "etc_09_letter"
    case etc_10_check = "etc_10_check"
    case etc_11_lightBulb = "etc_11_lightBulb"
    case etc_12_moustache = "etc_12_moustache"
    case etc_13_lock = "etc_13_lock"
    
    case nature_01_cat = "nature_01_cat"
    case nature_02_dog = "nature_02_dog"
    case nature_03_petPaw = "nature_03_petPaw"
    case nature_04_tree = "nature_04_tree"
    case nature_05_quill = "nature_05_quill"
    case nature_06_sun = "nature_06_sun"
    case nature_07_cloud = "nature_07_cloud"
    case nature_08_lightning = "nature_08_lightning"
    case nature_09_umbrella = "nature_09_umbrella"
    case nature_10_snow = "nature_10_snow"
    case nature_11_fire = "nature_11_fire"
    
    var imageName: String {
        switch self {
        case .activity_01_brush: return "ic_category_activity_01_brush"
        case .activity_02_robot: return "ic_category_activity_02_robot"
        case .activity_03_controller_wireless: return "ic_category_activity_03_controller_wireless"
        case .activity_04_camera: return "ic_category_activity_04_camera"
        case .activity_05_mike: return "ic_category_activity_05_mike"
        case .activity_06_camera_video: return "ic_category_activity_06_camera_video"
        case .activity_07_groupRunning: return "ic_category_activity_07_groupRunning"
        case .activity_08_yoga: return "ic_category_activity_08_yoga"
        case .activity_09_fitnessBicycle: return "ic_category_activity_09_fitnessBicycle"
        case .activity_10_golfHole: return "ic_category_activity_10_golfHole"
        case .activity_11_baseball_batBall: return "ic_category_activity_11_baseball_batBall"
        case .activity_12_bowlingSet: return "ic_category_activity_12_bowlingSet"
        case .activity_13_tambourine: return "ic_category_activity_13_tambourine"
        case .activity_14_headphones: return "ic_category_activity_14_headphones"
        case .daily_01_coffee_mug: return "ic_category_daily_01_coffee_mug"
        case .daily_02_wine: return "ic_category_daily_02_wine"
        case .daily_03_forkSpoon: return "ic_category_daily_03_forkSpoon"
        case .daily_04_chicken: return "ic_category_daily_04_chicken"
        case .daily_05_burger: return "ic_category_daily_05_burger"
        case .daily_06_donut: return "ic_category_daily_06_donut"
        case .daily_07_strawberry: return "ic_category_daily_07_strawberry"
        case .daily_08_waterMelon: return "ic_category_daily_08_waterMelon"
        case .daily_09_carrot: return "ic_category_daily_09_carrot"
        case .daily_10_smoking: return "ic_category_daily_10_smoking"
        case .daily_11_bicycle: return "ic_category_daily_11_bicycle"
        case .daily_12_car: return "ic_category_daily_12_car"
        case .daily_13_bus: return "ic_category_daily_13_bus"
        case .daily_14_airplane: return "ic_category_daily_14_airplane"
        case .daily_15_baggage: return "ic_category_daily_15_baggage"
        case .daily_16_beach: return "ic_category_daily_16_beach"
        case .daily_17_medicalBandage: return "ic_category_daily_17_medicalBandage"
        case .daily_18_money: return "ic_category_daily_18_money"
        case .daily_19_money_piggy: return "ic_category_daily_19_money_piggy"
        case .daily_20_shoppingCart: return "ic_category_daily_20_shoppingCart"
        case .daily_21_shoppingBasket: return "ic_category_daily_21_shoppingBasket"
        case .daily_22_gift: return "ic_category_daily_22_gift"
        case .daily_23_home: return "ic_category_daily_23_home"
        case .daily_24_location_pin: return "ic_category_daily_24_location_pin"
        case .daily_25_location_user: return "ic_category_daily_25_location_user"
        case .emotion_01_emojiFace: return "ic_category_emotion_01_emojiFace"
        case .emotion_02_emojiSad: return "ic_category_emotion_02_emojiSad"
        case .emotion_03_emojiCheerful: return "ic_category_emotion_03_emojiCheerful"
        case .emotion_04_emojiLol: return "ic_category_emotion_04_emojiLol"
        case .emotion_05_emojiExcited: return "ic_category_emotion_05_emojiExcited"
        case .emotion_06_emojiHungry: return "ic_category_emotion_06_emojiHungry"
        case .emotion_07_emojiDevastated: return "ic_category_emotion_07_emojiDevastated"
        case .emotion_08_alien: return "ic_category_emotion_08_alien"
        case .emotion_09_skull: return "ic_category_emotion_09_skull"
        case .emotion_10_chatSmiley: return "ic_category_emotion_10_chatSmiley"
        case .emotion_11_handOk: return "ic_category_emotion_11_handOk"
        case .emotion_12_thumbsUp: return "ic_category_emotion_12_thumbsUp"
        case .emotion_13_star: return "ic_category_emotion_13_star"
        case .emotion_14_heart: return "ic_category_emotion_14_heart"
        case .emotion_15_heartBreak: return "ic_category_emotion_15_heartBreak"
        case .emotion_16_chatSquare_warning: return "ic_category_emotion_16_chatSquare_warning"
        case .emotion_17_chatSquare_question: return "ic_category_emotion_17_chatSquare_question"
        case .emotion_18_magicWand: return "ic_category_emotion_18_magicWand"
        case .emotion_19_twinkle: return "ic_category_emotion_19_twinkle"
        case .etc_01_bookmark: return "ic_category_etc_01_bookmark"
        case .etc_02_cursorArrow1: return "ic_category_etc_02_cursorArrow1"
        case .etc_03_cursorArrow2: return "ic_category_etc_03_cursorArrow2"
        case .etc_04_bell: return "ic_category_etc_04_bell"
        case .etc_05_megaPhone: return "ic_category_etc_05_megaPhone"
        case .etc_06_loading: return "ic_category_etc_06_loading"
        case .etc_07_phone: return "ic_category_etc_07_phone"
        case .etc_08_twoBubbles: return "ic_category_etc_08_twoBubbles"
        case .etc_09_letter: return "ic_category_etc_09_letter"
        case .etc_10_check: return "ic_category_etc_10_check"
        case .etc_11_lightBulb: return "ic_category_etc_11_lightBulb"
        case .etc_12_moustache: return "ic_category_etc_12_moustache"
        case .etc_13_lock: return "ic_category_etc_13_lock"
        case .nature_01_cat: return "ic_category_nature_01_cat"
        case .nature_02_dog: return "ic_category_nature_02_dog"
        case .nature_03_petPaw: return "ic_category_nature_03_petPaw"
        case .nature_04_tree: return "ic_category_nature_04_tree"
        case .nature_05_quill: return "ic_category_nature_05_quill"
        case .nature_06_sun: return "ic_category_nature_06_sun"
        case .nature_07_cloud: return "ic_category_nature_07_cloud"
        case .nature_08_lightning: return "ic_category_nature_08_lightning"
        case .nature_09_umbrella: return "ic_category_nature_09_umbrella"
        case .nature_10_snow: return "ic_category_nature_10_snow"
        case .nature_11_fire: return "ic_category_nature_11_fire"
        }
    }
}
