//
//  TripIcon.swift
//  Footprint
//
//  Created by sandy on 11/12/24.
//

import Foundation

enum TripIcon: String, Equatable, Hashable {
    case ic_concept_01_smile = "ic_concept_01_smile"
    case ic_concept_02_prank = "ic_concept_02_prank"
    case ic_concept_03_lol = "ic_concept_03_lol"
    case ic_concept_04_unhappy = "ic_concept_04_unhappy"
    case ic_concept_05_disapointed = "ic_concept_05_disapointed"
    case ic_concept_06_mad = "ic_concept_06_mad"
    case ic_concept_07_like = "ic_concept_07_like"
    case ic_concept_08_dislike = "ic_concept_08_dislike"
    case ic_concept_09_noHand = "ic_concept_09_noHand"
    case ic_concept_10_star = "ic_concept_10_star"
    case ic_concept_11_heart = "ic_concept_11_heart"
    case ic_concept_12_clover = "ic_concept_12_clover"
    case ic_concept_13_square = "ic_concept_13_square"
    case ic_concept_14_circle = "ic_concept_14_circle"
    case ic_concept_15_triangle = "ic_concept_15_triangle"
    case ic_concept_16_diamond = "ic_concept_16_diamond"
    case ic_concept_17_tripRoad = "ic_concept_17_tripRoad"
    case ic_concept_18_earthStar = "ic_concept_18_earthStar"
    case ic_concept_19_car = "ic_concept_19_car"
    case ic_concept_20_bus = "ic_concept_20_bus"
    case ic_concept_21_bicycle = "ic_concept_21_bicycle"
    case ic_concept_22_metro = "ic_concept_22_metro"
    case ic_concept_23_plane = "ic_concept_23_plane"
    case ic_concept_24_amusementPark = "ic_concept_24_amusementPark"
    case ic_concept_25_confetti = "ic_concept_25_confetti"
    case ic_concept_26_movie = "ic_concept_26_movie"
    case ic_concept_27_restaurantDishes = "ic_concept_27_restaurantDishes"
    case ic_concept_28_iceCream = "ic_concept_28_iceCream"
    case ic_concept_29_coffee = "ic_concept_29_coffee"
    case ic_concept_30_bread = "ic_concept_30_bread"
    case ic_concept_31_cocktail = "ic_concept_31_cocktail"
    case ic_concept_32_champagne = "ic_concept_32_champagne"
    case ic_concept_33_walking = "ic_concept_33_walking"
    case ic_concept_34_running = "ic_concept_34_running"
    case ic_concept_35_yoga = "ic_concept_35_yoga"
    case ic_concept_36_fitnessShaker = "ic_concept_36_fitnessShaker"
    case ic_concept_37_fitnessBicycle = "ic_concept_37_fitnessBicycle"
    case ic_concept_38_athleticsRunning = "ic_concept_38_athleticsRunning"
    case ic_concept_39_golfHole = "ic_concept_39_golfHole"
    case ic_concept_40_soccerField = "ic_concept_40_soccerField"
    case ic_concept_41_bookmark = "ic_concept_41_bookmark"
    case ic_concept_42_paperEdit = "ic_concept_42_paperEdit"
    case ic_concept_43_tags = "ic_concept_43_tags"
    case ic_concept_44_awardRibbonStar = "ic_concept_44_awardRibbonStar"
    case ic_concept_45_rankingStarsRibbon = "ic_concept_45_rankingStarsRibbon"
    case ic_concept_46_fire = "ic_concept_46_fire"
    case ic_concept_47_music = "ic_concept_47_music"
    case ic_concept_48_spaceAstronaut = "ic_concept_48_spaceAstronaut"
    case ic_concept_49_house = "ic_concept_49_house"
    case ic_concept_50_officeOutdoors = "ic_concept_50_officeOutdoors"
    case ic_concept_51_stampsImage = "ic_concept_51_stampsImage"
    case ic_concept_52_camera = "ic_concept_52_camera"
    case ic_concept_53_accountingBillStack = "ic_concept_53_accountingBillStack"
    case ic_concept_54_shoppingCart = "ic_concept_54_shoppingCart"
    case ic_concept_55_medical = "ic_concept_55_medical"
    case ic_concept_56_capsule = "ic_concept_56_capsule"
    case ic_concept_57_bandageLeg = "ic_concept_57_bandageLeg"
    case ic_concept_58_cloudSnow = "ic_concept_58_cloudSnow"
    case ic_concept_59_cloud = "ic_concept_59_cloud"
    case ic_concept_60_umbrella = "ic_concept_60_umbrella"
    case ic_concept_61_sun = "ic_concept_61_sun"
    case ic_concept_62_nightMoon = "ic_concept_62_nightMoon"
    case ic_concept_63_natural = "ic_concept_63_natural"
    case ic_concept_64_google = "ic_concept_64_google"
    case ic_concept_65_instagram = "ic_concept_65_instagram"
    case ic_concept_66_facebook = "ic_concept_66_facebook"
    case ic_concept_67_youtube = "ic_concept_67_youtube"
    
    var imageName: String {
        switch self {
        case .ic_concept_01_smile: return "ic_concept_01_smile"
        case .ic_concept_02_prank: return "ic_concept_02_prank"
        case .ic_concept_03_lol: return "ic_concept_03_lol"
        case .ic_concept_04_unhappy: return "ic_concept_04_unhappy"
        case .ic_concept_05_disapointed: return "ic_concept_05_disapointed"
        case .ic_concept_06_mad: return "ic_concept_06_mad"
        case .ic_concept_07_like: return "ic_concept_07_like"
        case .ic_concept_08_dislike: return "ic_concept_08_dislike"
        case .ic_concept_09_noHand: return "ic_concept_09_noHand"
        case .ic_concept_10_star: return "ic_concept_10_star"
        case .ic_concept_11_heart: return "ic_concept_11_heart"
        case .ic_concept_12_clover: return "ic_concept_12_clover"
        case .ic_concept_13_square: return "ic_concept_13_square"
        case .ic_concept_14_circle: return "ic_concept_14_circle"
        case .ic_concept_15_triangle: return "ic_concept_15_triangle"
        case .ic_concept_16_diamond: return "ic_concept_16_diamond"
        case .ic_concept_17_tripRoad: return "ic_concept_17_tripRoad"
        case .ic_concept_18_earthStar: return "ic_concept_18_earthStar"
        case .ic_concept_19_car: return "ic_concept_19_car"
        case .ic_concept_20_bus: return "ic_concept_20_bus"
        case .ic_concept_21_bicycle: return "ic_concept_21_bicycle"
        case .ic_concept_22_metro: return "ic_concept_22_metro"
        case .ic_concept_23_plane: return "ic_concept_23_plane"
        case .ic_concept_24_amusementPark: return "ic_concept_24_amusementPark"
        case .ic_concept_25_confetti: return "ic_concept_25_confetti"
        case .ic_concept_26_movie: return "ic_concept_26_movie"
        case .ic_concept_27_restaurantDishes: return "ic_concept_27_restaurantDishes"
        case .ic_concept_28_iceCream: return "ic_concept_28_iceCream"
        case .ic_concept_29_coffee: return "ic_concept_29_coffee"
        case .ic_concept_30_bread: return "ic_concept_30_bread"
        case .ic_concept_31_cocktail: return "ic_concept_31_cocktail"
        case .ic_concept_32_champagne: return "ic_concept_32_champagne"
        case .ic_concept_33_walking: return "ic_concept_33_walking"
        case .ic_concept_34_running: return "ic_concept_34_running"
        case .ic_concept_35_yoga: return "ic_concept_35_yoga"
        case .ic_concept_36_fitnessShaker: return "ic_concept_36_fitnessShaker"
        case .ic_concept_37_fitnessBicycle: return "ic_concept_37_fitnessBicycle"
        case .ic_concept_38_athleticsRunning: return "ic_concept_38_athleticsRunning"
        case .ic_concept_39_golfHole: return "ic_concept_39_golfHole"
        case .ic_concept_40_soccerField: return "ic_concept_40_soccerField"
        case .ic_concept_41_bookmark: return "ic_concept_41_bookmark"
        case .ic_concept_42_paperEdit: return "ic_concept_42_paperEdit"
        case .ic_concept_43_tags: return "ic_concept_43_tags"
        case .ic_concept_44_awardRibbonStar: return "ic_concept_44_awardRibbonStar"
        case .ic_concept_45_rankingStarsRibbon: return "ic_concept_45_rankingStarsRibbon"
        case .ic_concept_46_fire: return "ic_concept_46_fire"
        case .ic_concept_47_music: return "ic_concept_47_music"
        case .ic_concept_48_spaceAstronaut: return "ic_concept_48_spaceAstronaut"
        case .ic_concept_49_house: return "ic_concept_49_house"
        case .ic_concept_50_officeOutdoors: return "ic_concept_50_officeOutdoors"
        case .ic_concept_51_stampsImage: return "ic_concept_51_stampsImage"
        case .ic_concept_52_camera: return "ic_concept_52_camera"
        case .ic_concept_53_accountingBillStack: return "ic_concept_53_accountingBillStack"
        case .ic_concept_54_shoppingCart: return "ic_concept_54_shoppingCart"
        case .ic_concept_55_medical: return "ic_concept_55_medical"
        case .ic_concept_56_capsule: return "ic_concept_56_capsule"
        case .ic_concept_57_bandageLeg: return "ic_concept_57_bandageLeg"
        case .ic_concept_58_cloudSnow: return "ic_concept_58_cloudSnow"
        case .ic_concept_59_cloud: return "ic_concept_59_cloud"
        case .ic_concept_60_umbrella: return "ic_concept_60_umbrella"
        case .ic_concept_61_sun: return "ic_concept_61_sun"
        case .ic_concept_62_nightMoon: return "ic_concept_62_nightMoon"
        case .ic_concept_63_natural: return "ic_concept_63_natural"
        case .ic_concept_64_google: return "ic_concept_64_google"
        case .ic_concept_65_instagram: return "ic_concept_65_instagram"
        case .ic_concept_66_facebook: return "ic_concept_66_facebook"
        case .ic_concept_67_youtube: return "ic_concept_67_youtube"
        }
    }
}
